In [6]:
import pandas as pd

race_results = pd.read_csv("../data/raw/race_results/british_gp_2025.csv")
q_results = pd.read_csv("../data/raw/qualifying/british_gp_2025.csv")
laps = pd.read_csv("../data/raw/laps/british_gp_2025.csv")
stints = pd.read_csv("../data/raw/stints/british_gp_2025.csv")
pit_stops = pd.read_csv("../data/raw/pit_stops/british_gp_2025.csv")
weather = pd.read_csv("../data/raw/weather/british_gp_2025.csv")

print("All six datasets loaded successfully!")

All six datasets loaded successfully!

In [7]:
datasets = {
    "RACE RESULTS": race_results,
    "QUALIFYING": q_results,
    "LAPS": laps,
    "STINTS": stints,
    "PIT STOPS": pit_stops,
    "WEATHER": weather
}

for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)
    print(df.columns.tolist())

============================================================
RACE RESULTS
============================================================
['DriverNumber', 'BroadcastName', 'Abbreviation', 'DriverId', 'TeamName', 'TeamColor', 'TeamId', 'FirstName', 'LastName', 'FullName', 'HeadshotUrl', 'CountryCode', 'Position', 'ClassifiedPosition', 'GridPosition', 'Q1', 'Q2', 'Q3', 'Time', 'Status', 'Points', 'Laps']

============================================================
QUALIFYING
============================================================
['DriverNumber', 'BroadcastName', 'Abbreviation', 'DriverId', 'TeamName', 'TeamColor', 'TeamId', 'FirstName', 'LastName', 'FullName', 'HeadshotUrl', 'CountryCode', 'Position', 'ClassifiedPosition', 'GridPosition', 'Q1', 'Q2', 'Q3', 'Time', 'Status', 'Points', 'Laps']

============================================================
LAPS
============================================================
['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint', 'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time', 'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime', 'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest', 'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime', 'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason', 'FastF1Generated', 'IsAccurate']

============================================================
STINTS
============================================================
['Driver', 'LapNumber', 'LapTime', 'Compound', 'TyreLife', 'Stint']

============================================================
PIT STOPS
============================================================
['Driver', 'LapNumber', 'PitInTime', 'PitOutTime']

============================================================
WEATHER
============================================================
['Time', 'AirTemp', 'Humidity', 'Pressure', 'Rainfall', 'TrackTemp', 'WindDirection', 'WindSpeed']

In [11]:
for name, df in datasets.items():
    print("\n"+ "="*60)
    print(name)
    print("="*60)
    print(df.isnull().sum())

============================================================
RACE RESULTS
============================================================
DriverNumber           0
BroadcastName          0
Abbreviation           0
DriverId               0
TeamName               0
TeamColor              0
TeamId                 0
FirstName              0
LastName               0
FullName               0
HeadshotUrl            1
CountryCode           20
Position               0
ClassifiedPosition     0
GridPosition           0
Q1                    20
Q2                    20
Q3                    20
Time                   5
Status                 0
Points                 0
Laps                   0
dtype: int64

============================================================
QUALIFYING
============================================================
DriverNumber           0
BroadcastName          0
Abbreviation           0
DriverId               0
TeamName               0
TeamColor              0
TeamId                 0
FirstName              0
LastName               0
FullName               0
HeadshotUrl            1
CountryCode           20
Position               0
ClassifiedPosition    20
GridPosition          20
Q1                     0
Q2                     5
Q3                    10
Time                  20
Status                20
Points                20
Laps                  20
dtype: int64

============================================================
LAPS
============================================================
Time                    0
Driver                  0
DriverNumber            0
LapTime                91
LapNumber               0
Stint                   0
PitOutTime            785
PitInTime             789
Sector1Time            21
Sector2Time             3
Sector3Time             3
Sector1SessionTime     23
Sector2SessionTime      3
Sector3SessionTime      3
SpeedI1                 3
SpeedI2                 3
SpeedFL                39
SpeedST                 3
IsPersonalBest          2
Compound                0
TyreLife                0
FreshTyre               0
Team                    0
LapStartTime            0
LapStartDate            0
TrackStatus             0
Position                3
Deleted                 0
DeletedReason         812
FastF1Generated         0
IsAccurate              0
dtype: int64

============================================================
STINTS
============================================================
Driver        0
LapNumber     0
LapTime      91
Compound      0
TyreLife      0
Stint         0
dtype: int64

============================================================
PIT STOPS
============================================================
Driver         0
LapNumber      0
PitInTime      0
PitOutTime    36
dtype: int64

============================================================
WEATHER
============================================================
Time             0
AirTemp          0
Humidity         0
Pressure         0
Rainfall         0
TrackTemp        0
WindDirection    0
WindSpeed        0
dtype: int64

In [13]:
for name,df in datasets.items():
    print("\n"+"="*60)
    print(name)
    print(("="*60))
    print("Duplicated rows:",df.duplicated().sum())

============================================================
RACE RESULTS
============================================================
Duplicated rows: 0

============================================================
QUALIFYING
============================================================
Duplicated rows: 0

============================================================
LAPS
============================================================
Duplicated rows: 0

============================================================
STINTS
============================================================
Duplicated rows: 0

============================================================
PIT STOPS
============================================================
Duplicated rows: 0

============================================================
WEATHER
============================================================
Duplicated rows: 0

In [15]:
for name,df in datasets.items():
    print("\n" + "="*60)
    print(name)
    print("="*60)
    print(df.head(4))

============================================================
RACE RESULTS
============================================================
   DriverNumber BroadcastName Abbreviation    DriverId     TeamName TeamColor  \
0             4      L NORRIS          NOR      norris      McLaren    F47600
1            81     O PIASTRI          PIA     piastri      McLaren    F47600
2            27  N HULKENBERG          HUL  hulkenberg  Kick Sauber    01C00E
3            44    L HAMILTON          HAM    hamilton      Ferrari    ED1131

    TeamId FirstName    LastName         FullName  ... Position  \
0  mclaren     Lando      Norris     Lando Norris  ...      1.0
1  mclaren     Oscar     Piastri    Oscar Piastri  ...      2.0
2   sauber      Nico  Hulkenberg  Nico Hulkenberg  ...      3.0
3  ferrari     Lewis    Hamilton   Lewis Hamilton  ...      4.0

   ClassifiedPosition  GridPosition  Q1  Q2  Q3                    Time  \
0                   1           3.0 NaN NaN NaN  0 days 01:37:15.735000
1                   2           2.0 NaN NaN NaN  0 days 00:00:06.812000
2                   3          19.0 NaN NaN NaN  0 days 00:00:34.742000
3                   4           5.0 NaN NaN NaN  0 days 00:00:39.812000

     Status Points  Laps
0  Finished   25.0  52.0
1  Finished   18.0  52.0
2  Finished   15.0  52.0
3  Finished   12.0  52.0

[4 rows x 22 columns]

============================================================
QUALIFYING
============================================================
   DriverNumber BroadcastName Abbreviation        DriverId         TeamName  \
0             1  M VERSTAPPEN          VER  max_verstappen  Red Bull Racing
1            81     O PIASTRI          PIA         piastri          McLaren
2             4      L NORRIS          NOR          norris          McLaren
3            63     G RUSSELL          RUS         russell         Mercedes

  TeamColor    TeamId FirstName    LastName        FullName  ... Position  \
0    4781D7  red_bull       Max  Verstappen  Max Verstappen  ...      1.0
1    F47600   mclaren     Oscar     Piastri   Oscar Piastri  ...      2.0
2    F47600   mclaren     Lando      Norris    Lando Norris  ...      3.0
3    00D7B6  mercedes    George     Russell  George Russell  ...      4.0

   ClassifiedPosition  GridPosition                      Q1  \
0                 NaN           NaN  0 days 00:01:25.886000
1                 NaN           NaN  0 days 00:01:25.963000
2                 NaN           NaN  0 days 00:01:26.123000
3                 NaN           NaN  0 days 00:01:26.236000

                       Q2                      Q3 Time Status  Points  Laps
0  0 days 00:01:25.316000  0 days 00:01:24.892000  NaN    NaN     NaN   NaN
1  0 days 00:01:25.316000  0 days 00:01:24.995000  NaN    NaN     NaN   NaN
2  0 days 00:01:25.231000  0 days 00:01:25.010000  NaN    NaN     NaN   NaN
3  0 days 00:01:25.637000  0 days 00:01:25.029000  NaN    NaN     NaN   NaN

[4 rows x 22 columns]

============================================================
LAPS
============================================================
                     Time Driver  DriverNumber                 LapTime  \
0  0 days 00:57:55.042000    VER             1  0 days 00:01:45.820000
1  0 days 01:00:10.640000    VER             1  0 days 00:02:15.598000
2  0 days 01:02:27.997000    VER             1  0 days 00:02:17.357000
3  0 days 01:04:13.565000    VER             1  0 days 00:01:45.568000

   LapNumber  Stint PitOutTime PitInTime             Sector1Time  \
0        1.0    1.0        NaN       NaN                     NaN
1        2.0    1.0        NaN       NaN  0 days 00:00:45.755000
2        3.0    1.0        NaN       NaN  0 days 00:00:48.885000
3        4.0    1.0        NaN       NaN  0 days 00:00:36.223000

              Sector2Time  ... FreshTyre             Team  \
0  0 days 00:00:41.707000  ...      True  Red Bull Racing
1  0 days 00:00:53.700000  ...      True  Red Bull Racing
2  0 days 00:00:50.924000  ...      True  Red Bull Racing
3  0 days 00:00:40.712000  ...      True  Red Bull Racing

             LapStartTime             LapStartDate  TrackStatus  Position  \
0  0 days 00:56:09.003000  2025-07-06 14:03:49.616           12       1.0
1  0 days 00:57:55.042000  2025-07-06 14:05:35.655           26       1.0
2  0 days 01:00:10.640000  2025-07-06 14:07:51.253            6       1.0
3  0 days 01:02:27.997000  2025-07-06 14:10:08.610         6712       1.0

   Deleted  DeletedReason FastF1Generated IsAccurate
0    False            NaN           False      False
1    False            NaN           False      False
2    False            NaN           False      False
3    False            NaN           False      False

[4 rows x 31 columns]

============================================================
STINTS
============================================================
  Driver  LapNumber                 LapTime      Compound  TyreLife  Stint
0    VER        1.0  0 days 00:01:45.820000  INTERMEDIATE       1.0    1.0
1    VER        2.0  0 days 00:02:15.598000  INTERMEDIATE       2.0    1.0
2    VER        3.0  0 days 00:02:17.357000  INTERMEDIATE       3.0    1.0
3    VER        4.0  0 days 00:01:45.568000  INTERMEDIATE       4.0    1.0

============================================================
PIT STOPS
============================================================
  Driver  LapNumber               PitInTime  PitOutTime
0    VER       11.0  0 days 01:17:23.948000         NaN
1    VER       41.0  0 days 02:16:41.355000         NaN
2    GAS       11.0  0 days 01:17:34.025000         NaN
3    GAS       41.0  0 days 02:16:43.664000         NaN

============================================================
WEATHER
============================================================
                     Time  AirTemp  Humidity  Pressure  Rainfall  TrackTemp  \
0  0 days 00:00:19.723000     18.0      85.0     988.6     False       24.2
1  0 days 00:01:19.675000     18.0      83.0     988.5     False       24.6
2  0 days 00:02:19.683000     18.1      82.0     988.6     False       24.6
3  0 days 00:03:19.685000     18.0      81.0     988.6     False       24.1

   WindDirection  WindSpeed
0            174        0.7
1            111        0.9
2             61        2.2
3             71        3.1

In [1]:
import pandas as pd

race_results = pd.read_csv(
    "../data/processed/master_race_results.csv"
)

race_counts = (
    race_results
    .groupby("Year")["Race"]
    .nunique()
)

print(race_counts)

Year
2020    17
2021     4
2022     2
2023    21
2024    24
2025    24
Name: Race, dtype: int64

In [2]:
import pandas as pd

race_results = pd.read_csv(
    "../data/processed/master_race_results.csv"
)

for year in [2021, 2022, 2023]:
    print(f"\n{'=' * 50}")
    print(f"{year}")
    print(f"{'=' * 50}")

    races = (
        race_results[race_results["Year"] == year]["Race"]
        .unique()
    )

    print(f"Collected: {len(races)}")
    
    for race in sorted(races):
        print("✓", race)

==================================================
2021
==================================================
Collected: 4
✓ bahrain grand prix
✓ emilia romagna grand prix
✓ portuguese grand prix
✓ spanish grand prix

==================================================
2022
==================================================
Collected: 2
✓ bahrain grand prix
✓ saudi arabian grand prix

==================================================
2023
==================================================
Collected: 21
✓ australian grand prix
✓ austrian grand prix
✓ azerbaijan grand prix
✓ bahrain grand prix
✓ belgian grand prix
✓ british grand prix
✓ canadian grand prix
✓ dutch grand prix
✓ hungarian grand prix
✓ italian grand prix
✓ japanese grand prix
✓ las vegas grand prix
✓ mexico city grand prix
✓ miami grand prix
✓ monaco grand prix
✓ qatar grand prix
✓ saudi arabian grand prix
✓ singapore grand prix
✓ spanish grand prix
✓ são paulo grand prix
✓ united states grand prix

In [1]:
from pathlib import Path

raw_race_folder = Path("../data/raw/race_results")

files = [
    file for file in raw_race_folder.glob("*.csv")
    if file.name.endswith("_grand_prix.csv")
]

print("Total race-result files:", len(files))

for year in range(2020, 2026):
    year_files = [
        file for file in files
        if file.name.startswith(str(year))
    ]

    print(f"{year}: {len(year_files)}")

Total race-result files: 131
2020: 17
2021: 22
2022: 22
2023: 22
2024: 24
2025: 24

In [2]:
from pathlib import Path

race_folder = Path("../data/raw/race_results")

files = [
    file for file in race_folder.glob("*.csv")
    if file.name.endswith("_grand_prix.csv")
]

print("Race folder:")
print(race_folder.resolve())

print("\nTotal files:", len(files))

for year in [2021, 2022, 2023]:
    year_files = [
        file for file in files
        if file.name.startswith(str(year))
    ]

    print(f"\n{year}: {len(year_files)}")
    for file in sorted(year_files):
        print(file.name)

Race folder:
C:\Users\chris\Desktop\APEX\data\raw\race_results

Total files: 131

2021: 22
2021_abu_dhabi_grand_prix.csv
2021_austrian_grand_prix.csv
2021_azerbaijan_grand_prix.csv
2021_bahrain_grand_prix.csv
2021_belgian_grand_prix.csv
2021_british_grand_prix.csv
2021_dutch_grand_prix.csv
2021_emilia_romagna_grand_prix.csv
2021_french_grand_prix.csv
2021_hungarian_grand_prix.csv
2021_italian_grand_prix.csv
2021_mexico_city_grand_prix.csv
2021_monaco_grand_prix.csv
2021_portuguese_grand_prix.csv
2021_qatar_grand_prix.csv
2021_russian_grand_prix.csv
2021_saudi_arabian_grand_prix.csv
2021_spanish_grand_prix.csv
2021_styrian_grand_prix.csv
2021_são_paulo_grand_prix.csv
2021_turkish_grand_prix.csv
2021_united_states_grand_prix.csv

2022: 22
2022_abu_dhabi_grand_prix.csv
2022_australian_grand_prix.csv
2022_austrian_grand_prix.csv
2022_azerbaijan_grand_prix.csv
2022_bahrain_grand_prix.csv
2022_belgian_grand_prix.csv
2022_british_grand_prix.csv
2022_canadian_grand_prix.csv
2022_dutch_grand_prix.csv
2022_emilia_romagna_grand_prix.csv
2022_french_grand_prix.csv
2022_hungarian_grand_prix.csv
2022_italian_grand_prix.csv
2022_japanese_grand_prix.csv
2022_mexico_city_grand_prix.csv
2022_miami_grand_prix.csv
2022_monaco_grand_prix.csv
2022_saudi_arabian_grand_prix.csv
2022_singapore_grand_prix.csv
2022_spanish_grand_prix.csv
2022_são_paulo_grand_prix.csv
2022_united_states_grand_prix.csv

2023: 22
2023_abu_dhabi_grand_prix.csv
2023_australian_grand_prix.csv
2023_austrian_grand_prix.csv
2023_azerbaijan_grand_prix.csv
2023_bahrain_grand_prix.csv
2023_belgian_grand_prix.csv
2023_british_grand_prix.csv
2023_canadian_grand_prix.csv
2023_dutch_grand_prix.csv
2023_hungarian_grand_prix.csv
2023_italian_grand_prix.csv
2023_japanese_grand_prix.csv
2023_las_vegas_grand_prix.csv
2023_mexico_city_grand_prix.csv
2023_miami_grand_prix.csv
2023_monaco_grand_prix.csv
2023_qatar_grand_prix.csv
2023_saudi_arabian_grand_prix.csv
2023_singapore_grand_prix.csv
2023_spanish_grand_prix.csv
2023_são_paulo_grand_prix.csv
2023_united_states_grand_prix.csv

In [3]:
from pathlib import Path
import pandas as pd

race_folder = Path("../data/raw/race_results")

for year in [2021, 2022, 2023]:
    print(f"\n{'=' * 50}")
    print(year)
    print(f"{'=' * 50}")

    files = sorted(
        file for file in race_folder.glob(f"{year}_*_grand_prix.csv")
    )

    for file in files:
        df = pd.read_csv(file)

        print(
            f"{file.name:<45} "
            f"rows={len(df):>2} "
            f"cols={len(df.columns):>2}"
        )

==================================================
2021
==================================================
2021_abu_dhabi_grand_prix.csv                 rows= 0 cols=22
2021_austrian_grand_prix.csv                  rows= 0 cols=22
2021_azerbaijan_grand_prix.csv                rows= 0 cols=22
2021_bahrain_grand_prix.csv                   rows=20 cols=22
2021_belgian_grand_prix.csv                   rows= 0 cols=22
2021_british_grand_prix.csv                   rows= 0 cols=22
2021_dutch_grand_prix.csv                     rows= 0 cols=22
2021_emilia_romagna_grand_prix.csv            rows=20 cols=22
2021_french_grand_prix.csv                    rows= 0 cols=22
2021_hungarian_grand_prix.csv                 rows= 0 cols=22
2021_italian_grand_prix.csv                   rows= 0 cols=22
2021_mexico_city_grand_prix.csv               rows= 0 cols=22
2021_monaco_grand_prix.csv                    rows= 0 cols=22
2021_portuguese_grand_prix.csv                rows=20 cols=22
2021_qatar_grand_prix.csv                     rows= 0 cols=22
2021_russian_grand_prix.csv                   rows= 0 cols=22
2021_saudi_arabian_grand_prix.csv             rows= 0 cols=22
2021_spanish_grand_prix.csv                   rows=20 cols=22
2021_styrian_grand_prix.csv                   rows= 0 cols=22
2021_são_paulo_grand_prix.csv                 rows= 0 cols=22
2021_turkish_grand_prix.csv                   rows= 0 cols=22
2021_united_states_grand_prix.csv             rows= 0 cols=22

==================================================
2022
==================================================
2022_abu_dhabi_grand_prix.csv                 rows= 0 cols=22
2022_australian_grand_prix.csv                rows= 0 cols=22
2022_austrian_grand_prix.csv                  rows= 0 cols=22
2022_azerbaijan_grand_prix.csv                rows= 0 cols=22
2022_bahrain_grand_prix.csv                   rows=20 cols=22
2022_belgian_grand_prix.csv                   rows= 0 cols=22
2022_british_grand_prix.csv                   rows= 0 cols=22
2022_canadian_grand_prix.csv                  rows= 0 cols=22
2022_dutch_grand_prix.csv                     rows= 0 cols=22
2022_emilia_romagna_grand_prix.csv            rows= 0 cols=22
2022_french_grand_prix.csv                    rows= 0 cols=22
2022_hungarian_grand_prix.csv                 rows= 0 cols=22
2022_italian_grand_prix.csv                   rows= 0 cols=22
2022_japanese_grand_prix.csv                  rows= 0 cols=22
2022_mexico_city_grand_prix.csv               rows= 0 cols=22
2022_miami_grand_prix.csv                     rows= 0 cols=22
2022_monaco_grand_prix.csv                    rows= 0 cols=22
2022_saudi_arabian_grand_prix.csv             rows=20 cols=22
2022_singapore_grand_prix.csv                 rows= 0 cols=22
2022_spanish_grand_prix.csv                   rows= 0 cols=22
2022_são_paulo_grand_prix.csv                 rows= 0 cols=22
2022_united_states_grand_prix.csv             rows= 0 cols=22

==================================================
2023
==================================================
2023_abu_dhabi_grand_prix.csv                 rows= 0 cols=22
2023_australian_grand_prix.csv                rows=20 cols=22
2023_austrian_grand_prix.csv                  rows=20 cols=22
2023_azerbaijan_grand_prix.csv                rows=20 cols=22
2023_bahrain_grand_prix.csv                   rows=20 cols=22
2023_belgian_grand_prix.csv                   rows=20 cols=22
2023_british_grand_prix.csv                   rows=20 cols=22
2023_canadian_grand_prix.csv                  rows=20 cols=22
2023_dutch_grand_prix.csv                     rows=20 cols=22
2023_hungarian_grand_prix.csv                 rows=20 cols=22
2023_italian_grand_prix.csv                   rows=20 cols=22
2023_japanese_grand_prix.csv                  rows=20 cols=22
2023_las_vegas_grand_prix.csv                 rows=20 cols=22
2023_mexico_city_grand_prix.csv               rows=20 cols=22
2023_miami_grand_prix.csv                     rows=20 cols=22
2023_monaco_grand_prix.csv                    rows=20 cols=22
2023_qatar_grand_prix.csv                     rows=20 cols=22
2023_saudi_arabian_grand_prix.csv             rows=20 cols=22
2023_singapore_grand_prix.csv                 rows=20 cols=22
2023_spanish_grand_prix.csv                   rows=20 cols=22
2023_são_paulo_grand_prix.csv                 rows=20 cols=22
2023_united_states_grand_prix.csv             rows=20 cols=22

In [4]:
from pathlib import Path
import pandas as pd

race_folder = Path("../data/raw/race_results")

for year in range(2020, 2026):
    files = list(
        race_folder.glob(f"{year}_*_grand_prix.csv")
    )

    non_empty = 0
    empty = 0

    for file in files:
        df = pd.read_csv(file)

        if len(df) > 0:
            non_empty += 1
        else:
            empty += 1

    print(
        f"{year}: {non_empty} non-empty | "
        f"{empty} empty"
    )

2020: 17 non-empty | 0 empty
2021: 22 non-empty | 0 empty
2022: 22 non-empty | 0 empty
2023: 22 non-empty | 0 empty
2024: 24 non-empty | 0 empty
2025: 24 non-empty | 0 empty

In [5]:
import pandas as pd

race_results = pd.read_csv(
    "../data/processed/master_race_results.csv"
)

print(
    race_results
    .groupby("Year")["Race"]
    .nunique()
)

Year
2020    17
2021     4
2022     2
2023    21
2024    24
2025    24
Name: Race, dtype: int64

In [6]:
import pandas as pd

race_results = pd.read_csv(
    "../data/processed/master_race_results.csv"
)

qualifying = pd.read_csv(
    "../data/processed/master_qualifying_results.csv"
)

print("Race results:", race_results.shape)
print("Qualifying:", qualifying.shape)

Race results: (2618, 24)
Qualifying: (2619, 24)

In [7]:
race_missing = (
    race_results
    .isna()
    .sum()
    .sort_values(ascending=False)
)

print(race_missing)

qualifying_missing = (
    qualifying
    .isna()
    .sum()
    .sort_values(ascending=False)
)

print(qualifying_missing)

Q2                    2618
Q3                    2618
Q1                    2618
CountryCode           1261
Time                   712
HeadshotUrl             85
BroadcastName            3
TeamColor                3
GridPosition             3
Position                 3
FirstName                0
TeamId                   0
DriverNumber             0
Abbreviation             0
TeamName                 0
DriverId                 0
ClassifiedPosition       0
LastName                 0
FullName                 0
Status                   0
Points                   0
Laps                     0
Year                     0
Race                     0
dtype: int64
Status                2619
Time                  2619
Laps                  2619
Points                2619
ClassifiedPosition    2619
GridPosition          2619
Q3                    1356
CountryCode           1260
Q2                     709
HeadshotUrl             82
Q1                      70
Position                22
TeamId                  22
DriverId                22
DriverNumber             0
BroadcastName            0
FirstName                0
TeamColor                0
TeamName                 0
Abbreviation             0
FullName                 0
LastName                 0
Year                     0
Race                     0
dtype: int64

In [8]:
race_results[
    race_results["Position"].isna()
][
    [
        "Year",
        "Race",
        "FullName",
        "TeamName",
        "Position",
        "GridPosition",
        "Status",
        "Points",
        "Laps"
    ]
]

,Year,Race,FullName,TeamName,Position,GridPosition,Status,Points,Laps
359,2021,abu dhabi grand prix,Nikita Mazepin,Haas F1 Team,NaN,NaN,Illness,0.0,0.0
1139,2022,saudi arabian grand prix,Mick Schumacher,Haas F1 Team,NaN,NaN,Withdrew,0.0,0.0
1599,2023,singapore grand prix,Lance Stroll,Aston Martin,NaN,NaN,Withdrew,0.0,0.0

In [9]:
race_results[
    race_results["GridPosition"].isna()
][
    [
        "Year",
        "Race",
        "FullName",
        "TeamName",
        "Position",
        "GridPosition",
        "Status",
        "Points",
        "Laps"
    ]
]

,Year,Race,FullName,TeamName,Position,GridPosition,Status,Points,Laps
359,2021,abu dhabi grand prix,Nikita Mazepin,Haas F1 Team,NaN,NaN,Illness,0.0,0.0
1139,2022,saudi arabian grand prix,Mick Schumacher,Haas F1 Team,NaN,NaN,Withdrew,0.0,0.0
1599,2023,singapore grand prix,Lance Stroll,Aston Martin,NaN,NaN,Withdrew,0.0,0.0

In [10]:
race_results[
    race_results["Time"].isna()
]["Status"].value_counts()

Status
+1 Lap              294
Retired             157
Collision            42
+2 Laps              41
Accident             23
Collision damage     22
Power Unit           13
Engine               13
Gearbox              12
Did not start         9
Disqualified          9
Brakes                7
+3 Laps               6
Hydraulics            5
Withdrew              4
Suspension            4
Electronics           3
Undertray             3
Puncture              3
Fuel pressure         3
Water pressure        3
Power loss            2
Overheating           2
Illness               2
Turbo                 2
Mechanical            2
Water leak            2
Oil leak              2
Spun off              2
Transmission          1
Exhaust               1
Debris                1
Wheel                 1
Radiator              1
Electrical            1
Driveshaft            1
Wheel nut             1
+5 Laps               1
Damage                1
Fuel leak             1
Rear wing             1
Vibrations            1
Fuel pump             1
+6 Laps               1
Differential          1
Front wing            1
Cooling system        1
Water pump            1
Lapped                1
Name: count, dtype: int64

In [11]:
race_results[
    race_results["GridPosition"] == 0
][
    [
        "Year",
        "Race",
        "FullName",
        "TeamName",
        "Position",
        "GridPosition",
        "Status",
        "Points",
        "Laps"
    ]
].sort_values(["Year", "Race"])

,Year,Race,FullName,TeamName,Position,GridPosition,Status,Points,Laps
169,2020,hungarian grand prix,Kevin Magnussen,Haas F1 Team,10.0,0.0,+1 Lap,1.0,69.0
175,2020,hungarian grand prix,Romain Grosjean,Haas F1 Team,16.0,0.0,+1 Lap,0.0,69.0
292,2020,styrian grand prix,Romain Grosjean,Haas F1 Team,13.0,0.0,+1 Lap,0.0,70.0
315,2020,turkish grand prix,George Russell,Williams,16.0,0.0,+1 Lap,0.0,57.0
318,2020,turkish grand prix,Nicholas Latifi,Williams,19.0,0.0,Collision damage,0.0,39.0
404,2021,bahrain grand prix,Sergio Perez,Red Bull Racing,5.0,0.0,Finished,10.0,56.0
437,2021,belgian grand prix,Kimi Räikkönen,Alfa Romeo Racing,18.0,0.0,Finished,0.0,1.0
438,2021,belgian grand prix,Sergio Perez,Red Bull Racing,19.0,0.0,Finished,0.0,1.0
455,2021,british grand prix,Sergio Perez,Red Bull Racing,16.0,0.0,+1 Lap,0.0,51.0
467,2021,dutch grand prix,Sergio Perez,Red Bull Racing,8.0,0.0,+1 Lap,4.0,71.0
475,2021,dutch grand prix,Nicholas Latifi,Williams,16.0,0.0,+2 Laps,0.0,70.0
494,2021,emilia romagna grand prix,Sebastian Vettel,Aston Martin,15.0,0.0,Gearbox,0.0,61.0
512,2021,french grand prix,Yuki Tsunoda,AlphaTauri,13.0,0.0,+1 Lap,0.0,52.0
532,2021,hungarian grand prix,Antonio Giovinazzi,Alfa Romeo Racing,13.0,0.0,+1 Lap,0.0,69.0
558,2021,italian grand prix,Pierre Gasly,AlphaTauri,19.0,0.0,Suspension,0.0,3.0
559,2021,italian grand prix,Yuki Tsunoda,AlphaTauri,20.0,0.0,Brakes,0.0,0.0
731,2021,são paulo grand prix,Kimi Räikkönen,Alfa Romeo Racing,12.0,0.0,+1 Lap,0.0,70.0
830,2022,austrian grand prix,Valtteri Bottas,Alfa Romeo,11.0,0.0,+1 Lap,0.0,70.0
888,2022,belgian grand prix,Pierre Gasly,AlphaTauri,9.0,0.0,Finished,2.0,44.0
892,2022,belgian grand prix,Yuki Tsunoda,AlphaTauri,13.0,0.0,Finished,0.0,44.0
974,2022,emilia romagna grand prix,Guanyu Zhou,Alfa Romeo,15.0,0.0,+1 Lap,0.0,62.0
1011,2022,hungarian grand prix,Pierre Gasly,AlphaTauri,12.0,0.0,+1 Lap,0.0,69.0
1089,2022,miami grand prix,Lance Stroll,Aston Martin,10.0,0.0,Finished,1.0,57.0
1096,2022,miami grand prix,Sebastian Vettel,Aston Martin,17.0,0.0,Collision,0.0,54.0
1153,2022,singapore grand prix,George Russell,Mercedes,14.0,0.0,+2 Laps,0.0,57.0
1196,2022,são paulo grand prix,Yuki Tsunoda,AlphaTauri,17.0,0.0,+1 Lap,0.0,70.0
1210,2022,united states grand prix,Esteban Ocon,Alpine,11.0,0.0,Finished,0.0,56.0
1395,2023,dutch grand prix,Kevin Magnussen,Haas F1 Team,16.0,0.0,Finished,0.0,72.0
1496,2023,mexico city grand prix,Lance Stroll,Aston Martin,17.0,0.0,Collision damage,0.0,66.0
1971,2024,mexico city grand prix,Esteban Ocon,Alpine,13.0,0.0,Lapped,0.0,70.0

In [12]:
qualifying[
    qualifying["Position"].isna()
][
    [
        "Year",
        "Race",
        "FullName",
        "TeamName",
        "Position",
        "Q1",
        "Q2",
        "Q3"
    ]
].sort_values(["Year", "Race"])

,Year,Race,FullName,TeamName,Position,Q1,Q2,Q3
599,2021,monaco grand prix,Mick Schumacher,Haas F1 Team,NaN,NaN,NaN,NaN
2079,2024,spanish grand prix,Max Verstappen,Red Bull Racing,NaN,NaN,NaN,NaN
2080,2024,spanish grand prix,Logan Sargeant,Williams,NaN,NaN,NaN,NaN
2081,2024,spanish grand prix,Daniel Ricciardo,RB,NaN,NaN,NaN,NaN
2082,2024,spanish grand prix,Lando Norris,McLaren,NaN,NaN,NaN,NaN
2083,2024,spanish grand prix,Pierre Gasly,Alpine,NaN,NaN,NaN,NaN
2084,2024,spanish grand prix,Sergio Perez,Red Bull Racing,NaN,NaN,NaN,NaN
2085,2024,spanish grand prix,Fernando Alonso,Aston Martin,NaN,NaN,NaN,NaN
2086,2024,spanish grand prix,Charles Leclerc,Ferrari,NaN,NaN,NaN,NaN
2087,2024,spanish grand prix,Lance Stroll,Aston Martin,NaN,NaN,NaN,NaN
2088,2024,spanish grand prix,Kevin Magnussen,Haas F1 Team,NaN,NaN,NaN,NaN
2089,2024,spanish grand prix,Yuki Tsunoda,RB,NaN,NaN,NaN,NaN
2090,2024,spanish grand prix,Alexander Albon,Williams,NaN,NaN,NaN,NaN
2091,2024,spanish grand prix,Guanyu Zhou,Kick Sauber,NaN,NaN,NaN,NaN
2092,2024,spanish grand prix,Nico Hulkenberg,Haas F1 Team,NaN,NaN,NaN,NaN
2093,2024,spanish grand prix,Esteban Ocon,Alpine,NaN,NaN,NaN,NaN
2094,2024,spanish grand prix,Lewis Hamilton,Mercedes,NaN,NaN,NaN,NaN
2095,2024,spanish grand prix,Carlos Sainz,Ferrari,NaN,NaN,NaN,NaN
2096,2024,spanish grand prix,George Russell,Mercedes,NaN,NaN,NaN,NaN
2097,2024,spanish grand prix,Valtteri Bottas,Kick Sauber,NaN,NaN,NaN,NaN
2098,2024,spanish grand prix,Oscar Piastri,McLaren,NaN,NaN,NaN,NaN
2598,2025,são paulo grand prix,Gabriel Bortoleto,Kick Sauber,NaN,NaN,NaN,NaN

In [13]:
race_results.duplicated(
    subset=["Year", "Race", "DriverId"]
).sum()

race_results[
    race_results.duplicated(
        subset=["Year", "Race", "DriverId"],
        keep=False
    )
].sort_values(["Year", "Race", "DriverId"])

Empty DataFrame
Columns: [DriverNumber, BroadcastName, Abbreviation, DriverId, TeamName, TeamColor, TeamId, FirstName, LastName, FullName, HeadshotUrl, CountryCode, Position, ClassifiedPosition, GridPosition, Q1, Q2, Q3, Time, Status, Points, Laps, Year, Race]
Index: []

[0 rows x 24 columns]

In [14]:
import pandas as pd

race = pd.read_csv("../data/processed/cleaned_race_results.csv")

print(race.shape)
print(race.columns.tolist())

(2618, 20)
['DriverNumber', 'Abbreviation', 'DriverId', 'TeamName', 'TeamId', 'FirstName', 'LastName', 'FullName', 'Position', 'ClassifiedPosition', 'GridPosition', 'Q1', 'Q2', 'Q3', 'Time', 'Status', 'Points', 'Laps', 'Year', 'Race']

In [15]:
print(race.isna().sum())

DriverNumber             0
Abbreviation             0
DriverId                 0
TeamName                 0
TeamId                   0
FirstName                0
LastName                 0
FullName                 0
Position                 3
ClassifiedPosition       0
GridPosition             3
Q1                    2618
Q2                    2618
Q3                    2618
Time                   712
Status                   0
Points                   0
Laps                     0
Year                     0
Race                     0
dtype: int64

In [16]:
race = pd.read_csv("../data/processed/cleaned_race_results.csv")

print(race.shape)
print(race.isna().sum())

(2618, 17)
DriverNumber            0
Abbreviation            0
DriverId                0
TeamName                0
TeamId                  0
FirstName               0
LastName                0
FullName                0
Position                3
ClassifiedPosition      0
GridPosition            3
Time                  712
Status                  0
Points                  0
Laps                    0
Year                    0
Race                    0
dtype: int64

In [17]:
qualifying = pd.read_csv(
    "../data/processed/master_qualifying_results.csv"
)

print(qualifying.shape)
print(qualifying.columns.tolist())
qualifying.head()

(2619, 24)
['DriverNumber', 'BroadcastName', 'Abbreviation', 'DriverId', 'TeamName', 'TeamColor', 'TeamId', 'FirstName', 'LastName', 'FullName', 'HeadshotUrl', 'CountryCode', 'Position', 'ClassifiedPosition', 'GridPosition', 'Q1', 'Q2', 'Q3', 'Time', 'Status', 'Points', 'Laps', 'Year', 'Race']

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps,Year,Race
0,77,V BOTTAS,BOT,bottas,Mercedes,00D2BE,mercedes,Valtteri,Bottas,Valtteri Bottas,...,NaN,0 days 00:01:26.738000,0 days 00:01:25.785000,0 days 00:01:25.154000,NaN,NaN,NaN,NaN,2020,70th anniversary grand prix
1,44,L HAMILTON,HAM,hamilton,Mercedes,00D2BE,mercedes,Lewis,Hamilton,Lewis Hamilton,...,NaN,0 days 00:01:26.818000,0 days 00:01:26.266000,0 days 00:01:25.217000,NaN,NaN,NaN,NaN,2020,70th anniversary grand prix
2,27,N HULKENBERG,HUL,hulkenberg,Racing Point,F596C8,racing_point,Nico,Hulkenberg,Nico Hulkenberg,...,NaN,0 days 00:01:27.279000,0 days 00:01:26.261000,0 days 00:01:26.082000,NaN,NaN,NaN,NaN,2020,70th anniversary grand prix
3,33,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,1E41FF,red_bull,Max,Verstappen,Max Verstappen,...,NaN,0 days 00:01:27.154000,0 days 00:01:26.779000,0 days 00:01:26.176000,NaN,NaN,NaN,NaN,2020,70th anniversary grand prix
4,3,D RICCIARDO,RIC,ricciardo,Renault,FFF500,renault,Daniel,Ricciardo,Daniel Ricciardo,...,NaN,0 days 00:01:27.442000,0 days 00:01:26.636000,0 days 00:01:26.297000,NaN,NaN,NaN,NaN,2020,70th anniversary grand prix

In [18]:
print(qualifying[["Q1", "Q2", "Q3"]].dtypes)
print(qualifying[["Q1", "Q2", "Q3"]].isna().sum())
print(qualifying[["Q1","Q2","Q3"]].head(10))

Q1    object
Q2    object
Q3    object
dtype: object
Q1      70
Q2     709
Q3    1356
dtype: int64
                       Q1                      Q2                      Q3
0  0 days 00:01:26.738000  0 days 00:01:25.785000  0 days 00:01:25.154000
1  0 days 00:01:26.818000  0 days 00:01:26.266000  0 days 00:01:25.217000
2  0 days 00:01:27.279000  0 days 00:01:26.261000  0 days 00:01:26.082000
3  0 days 00:01:27.154000  0 days 00:01:26.779000  0 days 00:01:26.176000
4  0 days 00:01:27.442000  0 days 00:01:26.636000  0 days 00:01:26.297000
5  0 days 00:01:27.187000  0 days 00:01:26.674000  0 days 00:01:26.428000
6  0 days 00:01:27.154000  0 days 00:01:26.523000  0 days 00:01:26.534000
7  0 days 00:01:27.427000  0 days 00:01:26.709000  0 days 00:01:26.614000
8  0 days 00:01:27.153000  0 days 00:01:26.642000  0 days 00:01:26.669000
9  0 days 00:01:27.217000  0 days 00:01:26.885000  0 days 00:01:26.778000

In [21]:
for col in ["Q1", "Q2", "Q3"]:
    qualifying[col] = pd.to_timedelta(
        qualifying[col],
        errors="coerce"
    ).dt.total_seconds()
qualifying[["Q1", "Q2", "Q3"]].head()

    Q1   Q2   Q3
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  0.0  0.0
4  0.0  0.0  0.0

In [22]:
qualifying = pd.read_csv(
    "../data/processed/master_qualifying_results.csv"
)

In [23]:
print(qualifying[["Q1", "Q2", "Q3"]].iloc[0])

Q1    0 days 00:01:26.738000
Q2    0 days 00:01:25.785000
Q3    0 days 00:01:25.154000
Name: 0, dtype: object

In [24]:
test = pd.to_timedelta(
    qualifying["Q1"],
    errors="coerce"
)

print(test.head())

0   0 days 00:01:26.738000
1   0 days 00:01:26.818000
2   0 days 00:01:27.279000
3   0 days 00:01:27.154000
4   0 days 00:01:27.442000
Name: Q1, dtype: timedelta64[ns]

In [25]:
print(test.dt.total_seconds().head())

0    86.738
1    86.818
2    87.279
3    87.154
4    87.442
Name: Q1, dtype: float64

In [26]:
for col in ["Q1", "Q2", "Q3"]:
    qualifying[col] = pd.to_timedelta(
        qualifying[col],
        errors="coerce"
    ).dt.total_seconds()

print(qualifying[["Q1", "Q2", "Q3"]].head())
print(qualifying[["Q1", "Q2", "Q3"]].dtypes)

       Q1      Q2      Q3
0  86.738  85.785  85.154
1  86.818  86.266  85.217
2  87.279  86.261  86.082
3  87.154  86.779  86.176
4  87.442  86.636  86.297
Q1    float64
Q2    float64
Q3    float64
dtype: object

In [27]:
print(qualifying[["Q1", "Q2", "Q3"]].isna().sum())

Q1      70
Q2     709
Q3    1356
dtype: int64